### PR TITLE
Update dnscrypt-resolvers.csv

### PR DESCRIPTION
**Pull request by fechterjm**
Added my server (DNSCrypt.is)

### CODE REVIEW

**Comment by jedisct1** [comment]
Merged. Thanks for the new server!

**Comment by jedisct1** [comment]
Do you really want the resolver name to be `ns0.dnscrypt.is`? Or just `dnscrypt.is`?

**Comment by fechterjm** [comment]
I'd like the name to be ns0.dnscrypt.is. I'm working on getting another resolver setup on another provider that will be ns1.dnscrypt.is

**Comment by jedisct1** [comment]
No problem!

Thanks a lot for setting this up!

**Comment by dnscryptme** [comment]
Hi @fechterjm,

your resolver is also listed on https://dnscrypt.me:8443/map.html

**Comment by fechterjm** [comment]
Hello,

Great! Thanks a lot for the help.

**Pull request merged**
