### PR TITLE
Added dnscrypt.ventricle.us to resolvers

### PR DESCRIPTION
**Pull request by JacobHenner**

### CODE REVIEW

**Comment by jedisct1** [comment]
Added, thanks!

**Comment by jedisct1** [comment]
Would you mind if the names (not the full names) were shortened a bit, by removing the `dnscrypt` part?

Just for consistency with other resolvers.

**Comment by JacobHenner** [comment]
@jedisct1 That'd be fine, I just figured I'd use their actual hostnames

**Comment by jedisct1** [comment]
Can you check that `v6.dnscrypt.ventricle.us` and `h.dnscrypt.ventricle.us` work?

They seem to be failing :(

**Comment by JacobHenner** [comment]
I'll confirm as soon as I'm in front of a computer again, but they all
seemed to work for me.

The one prefixed with the h only works over cjdns (as denoted in the CSV),
so unless you are connected to hyperboria, it won't work. If this
disqualifies it from inclusion in the list, it can be removed.

**Comment by JacobHenner** [comment]
Looks like there's an issue with the docker package and/or configuration, I'll try to resolve it later tonight. I incorrectly thought it was working properly because systemd wasn't running with the right address.

**Comment by JacobHenner** [comment]
I need to figure out how to properly run this over IPv6 using Docker, the standard NAT-style approach that works with protocols like HTTP does not work here. The ports are shown as open on the v6 addresses, but data is not being sent back to the client. Until this is resolved, these two should be removed. Sorry.

**Pull request merged**
