### PR TITLE
Update windows_service.c

### PR DESCRIPTION
**Pull request by GaneJ**
Add "IgnoreTimestamps (--ignore-timestamps)" and "LogLevel (--loglevel)" for windows service parameter registry.
So windows service parameter registry had the same option with the main program option.

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi Gane,

And thanks for your pull request.

In order for this to be merged, can you also include an update to the documentation to mention these new parameters?

Out of curiosity, what kind of platform do you need ignoring the certificates timestamps on? This features was really only designed as a temporary workaround for embedded systems with no battery-powered clock, so they can resolve names from NTP servers.

Thanks!

**Comment by GaneJ** [comment]
documentation? Do you mean this "README-WINDOWS.markdown" file?
OK. I'll update it.

what kind of platform do you need ignoring the certificates timestamps on?
First of all, to make Windows Service Registry Option synchronize with main program option.
Secondly, just in case someone need this feature/option to connected between windows client and non windows client (LAN).

**Comment by GaneJ** [comment]
"GaneJ closed this an hour ago"

Sorry, wrong button.

**Comment by jedisct1** [comment]
Merged, thanks!

**Pull request merged**
