### PR TITLE
Additional resolvers

### PR DESCRIPTION
**Pull request by neilwillgettoit**
I've added https://resolv.site beta servers sfo and nyc

### CODE REVIEW

**Comment by licaon-kter** [comment]
More info on this? Policy?

**Comment by neilwillgettoit** [comment]
@licaon-kter what would you like to know? It's a project I've been working on to block ads and tracking resource domains.

**Comment by licaon-kter** [comment]
That info. The site has no such info. Please add it (t)here.
No ads/tracking? What list do you use?
No logging?
Etc...

**Comment by neilwillgettoit** [comment]
Yes, I need to add this information to the site. 

The block list is generated from a bot that I have crawl/render various sites seeded from reddit to trap new ad/tracking domains. And then I review the bot's suggested blocks to make sure it does not break any site functionality. If it doesn't break anything, then I add it to the blocklist of resolv.site which then returns an nxdomain event for the ad/tracking domain. Some stuff I simply cannot block at the domain level because it would break site functionality, but for the majority of sites this works quite nicely to clean up browsing. 

No logging. I don't have dnssec extensions on right now. And I don't have any sort of namecoin resolution.

**Comment by licaon-kter** [comment]
> I don't have dnssec extensions on right now

Your PR says otherwise, better revise it then.

**Comment by neilwillgettoit** [comment]
When I run the conf I get: 

`$ ./dnscrypt-proxy -R resolv-east
`
`[INFO] - [resolv-east] does not support DNS Security Extensions`
`[INFO] + Provider supposedly doesn't keep logs`
`[NOTICE] Starting dnscrypt-proxy 1.6.1`
`[INFO] Generating a new session key pair`
`[INFO] Done`

**Comment by licaon-kter** [comment]
On your local machine maybe, the PR says ( https://github.com/neilwillgettoit/dnscrypt-proxy/blob/99e459f1f79b02b39647420a01443e6ecc00dee8/dnscrypt-resolvers.csv ): `yes,yes,no`

**Comment by neilwillgettoit** [comment]
Got it. I'll close this out and reopen with the corrections.

**Comment by jedisct1** [comment]
Hi,

`resolv-west` doesn't seem to be working. It doesn't even serve the certificate:

```bash
$ drill -p 8080 txt 2.dnscrypt-cert.west.beta.resolv.site @45.55.113.239
Error: error sending query: Could not send or receive, because of network error
```

**Comment by neilwillgettoit** [comment]
@jedisct1 fixed!

**Comment by jedisct1** [comment]
Re-added, thanks!

**Pull request merged**
