### PR TITLE
dns.d0wn.biz Server update

### PR DESCRIPTION
**Pull request by d0wnblog**
Update for dns.d0wn.biz servers... Many changes...

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks for the update!

These changes rename existing resolver identifiers (`d0wn-fr-ns1` -> `ns1.fr.dns.d0wn.biz`).

This is fine, but it is going to break dnscrypt for many people currently using one of your resolvers. When a non-existent resolver id has been configured, the OSX user interface picks a random resolver in the list. But with the Windows user interfaces and people using it from the command line, I think they will be left with a proxy that doesn't even start.

**Comment by jedisct1** [comment]
This also breaks tutorials :) http://linkis.com/blogspot.com/TV3U0

**Comment by jedisct1** [comment]
Merged, thanks!

**Comment by jedisct1** [comment]
`d0wn-de-ns1`, `d0wn-de-ns2`, `d0wn-vn-ns1`, `d0wn-pl-ns1`, `d0wn-dk-ns1`, `d0wn-al-ns1`  don't seem to be working :(

**Comment by d0wnblog** [comment]
Give me some minutes will check it. 

Am 2. August 2015 11:18:13 MESZ, schrieb Frank Denis <notifications@github.com>:

**Pull request merged**
