### PR TITLE
Configuration file

### PR DESCRIPTION
**Pull request by gijsbers**
Currently dnscrypt-proxy configuration is specified by command line options only.
Because a complete configuration may have to be copied to different systems, which may run different distributions or use different startup mechanisms, this can be cumbersome to handle. This pull request proposes to add options -c and -C to dnscrypt-proxy for supporting a configuration file. With option -c file options are read from file, while -C prints the configuration to stdout after all option processing has been completed. The latter allows for inspection of the final running configuration and to capture it to file for later reuse. This request also includes a fix to options_read_file to nul-terminate a file buffer.

### CODE REVIEW

**Comment by KrasnayaPloshchad** [comment]
This is awesome. With this function any clients would get a way to load, remenber and save the settings if the service is installed on Windows.

**Comment by KrasnayaPloshchad** [comment]
@gijsbers I found your branch is noticed having conflicts, can you fix it?

**Comment by jedisct1** [comment]
Having a configuration file is a really good idea.

A major advantage of a config file is that fact that it can include inline documentation.

Nobody likes to read too much documentation in order to get started.

Quickly review a sample config file and boom, make a few changes as you read the inline comments, and boom, you're good to go.

So I made a few changes to support a more classic configuration file, that is not automatically generated, but is a bit more flexible, and includes comments for every option.

The way plugins are configured could be better, though. Maybe by loading them all from the default folder, and letting them add their own rules to the parser.

**Comment by justinmayer** [comment]
In case anyone else comes across this pull request + commits and is confused why it does not work as described, this work was reverted in favor of an alternative implementation. See: https://github.com/jedisct1/dnscrypt-proxy#configuration-file

**Pull request merged**
