### PR TITLE
Add information on how to install it as a systemd service on Fedora

### PR DESCRIPTION
**Pull request by Kami**
This branch adds an example of how to install dnscrypt as a systemd service on Fedora and how to automatically start it on boot.

### CODE REVIEW

**Comment by mrwacky42** [comment]
Why not add this systemd file in packages/fpm and tweak the fpm.sh to include it?

**Comment by jedisct1** [comment]
Because fortunately, quite a few distributions are still not using systemd.

**Comment by jedisct1** [comment]
More seriously, a post-install script can be used to detect the presence of systemd and install (or not) the file.
But does the file actually work on all linux distros using systemd?
I'd rather keep the fpm-generated packages as generic as possible.

**Comment by Shnatsel** [comment]
JFYI I've implemented installation of systemd script along with proper registering of the service in the system in the Debian/Ubuntu package. The packaging now supports 3 different init systems at once: sysvinit, upstart and systemd. See #214 for the code drop.

**Pull request closed without merging**
