### PR TITLE
OpenRC support + adds index to README

### PR DESCRIPTION
**Pull request by CrisBRM**
OpenRC users need love too.

### CODE REVIEW

**Comment by jedisct1** [comment]
There are a few issues with this OpenRC script:
- It looks like it was only designed for Gentoo. I'm not sure it works on other platforms providing OpenRC either by default or as an option, such as Alpine Linux or FreeBSD.
- You should probably just let users set the resolver name instead of having to provide individual parameters.
- How to use plugins?

**Comment by CrisBRM** [comment]
* It's an init script for OpenRC and will work the same way on other platforms. I've tested it on Gentoo, Funtoo, and Calculate; I would hope alpine and so on use the same directories.

* That's certainly annoying, I agree. Will look into it.

* ```DNSCRYPT_OPTIONS="--plugin=/path/to/plugin --edns-payload-size=4096 --ephemeral-keys"```

**Comment by AliceGrey** [comment]
@jedisct1 @CrisBRM I know this pull has been open since Feb, are there any plans to implement this pull into dnscrypt-proxy? I currently use these scripts manually on Arch Linux with every dnscrypt-install.

**Comment by CrisBRM** [comment]
Update. 
I should add that it was designed for systems that use portage and openrc because the ebuild create a user and group for dnscrypt. So making it compatible would imply removing the user and group bits.
As for the other complaint, it reads from the csv file, so it's not an issue, you can just remove those parameters.

**Comment by jedisct1** [comment]
Can it be updated to use the config file?

**Comment by jedisct1** [comment]
It would be nice to have a new clean pull requests, without the changes to the README file, and that adds the file to the distribution tarball, and uses the config file.

**Pull request closed without merging**
