### PR TITLE
Update website and DNS for DNSCrypt Poland

### PR DESCRIPTION
**Pull request by pysiak**
It's just an update to update the legacy website and TXT records to the current ones. No functional changes, just steering people in the right direction.
I'll be changing the name from soltysiak (when it was just an experiment) to dnscrypt.pl when it became something bigger soon.
Thanks.

### CODE REVIEW

**Comment by jedisct1** [comment]
Merged, thanks!

**Comment by jedisct1** [comment]
Mmm... 178.216.201.222 doesn't seem to be answering queries on port 2053:
```
drill -p 2053 txt 2.dnscrypt-cert.poz.dnscrypt.pl @178.216.201.222                       
Error: error sending query: Could not send or receive, because of network error
```

**Comment by pysiak** [comment]
Port 2053 is dnscrypt-wrapper which is not configured to respond to non-dnscrypt queries.
You have to talk to the authoritative NS for dnscrypt.pl which is on port 53:
```
$ dig -p 53 txt 2.dnscrypt-cert.poz.dnscrypt.pl @178.216.201.222
; <<>> DiG 9.9.5-4~bpo70+1-Debian <<>> -p 53 txt 2.dnscrypt-cert.poz.dnscrypt.pl @178.216.201.222
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 470
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;2.dnscrypt-cert.poz.dnscrypt.pl. IN    TXT

;; ANSWER SECTION:
2.dnscrypt-cert.poz.dnscrypt.pl. 86400 IN TXT   "DNSC\000\001\000\000\139\2031\009\199J\208\213\016cA.$\1885\181D\174Z\003\211F\025<\191\133F\140\141\189O\031\021\004\196\2422m>\146\184}\008\027\235\019\176_p\240\010>M\211\176\176\247v\204o\248\007M\010\240\173\140\235R\197\141\205\002D\194\139U\010\186O{\219E\147o\025c\219r\211h:0\192\006\0187PYqwfzt0001T>|\014]\164}\142"

;; AUTHORITY SECTION:
dnscrypt.pl.            172800  IN      NS      fns1.42.pl.
dnscrypt.pl.            172800  IN      NS      fns2.42.pl.

;; Query time: 1 msec
;; SERVER: 178.216.201.222#53(178.216.201.222)
;; WHEN: Mon Oct 05 14:05:55 CEST 2015
;; MSG SIZE  rcvd: 238
```

Google responds with the cert file:
```
dig txt 2.dnscrypt-cert.poz.dnscrypt.pl @8.8.8.8
```

**Comment by jedisct1** [comment]
`dnscrypt-wrapper` doesn't even send the certificate?

I can't use the new configuration:

```bash
$ dnscrypt-proxy -L dnscrypt-resolvers.csv -R soltysiak --test 100
[INFO] + DNS Security Extensions are supported
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.6.0
[INFO] Generating a new session key pair
[INFO] Done
[ERROR] Unable to retrieve server certificates
```

**Comment by pysiak** [comment]
Ah yes, I changed the provider name from 2.dnscrypt-cert.soltysiak.com to 2.dnscrypt-cert.poz.dnscrypt.pl in the CSV, but dnscrypt-wrapper was still running with the old provider name.

I've setup an additional daemon with the new provider name on the same port.

Thanks to this little old patch it works: https://github.com/Cofyc/dnscrypt-wrapper/commit/a9e2157ccf73e9da46f2442ffe6d1e94dd88d01c

**Comment by pysiak** [comment]
Ah yes, I changed the provider name from 2.dnscrypt-cert.soltysiak.com to 2.dnscrypt-cert.poz.dnscrypt.pl in the CSV, but dnscrypt-wrapper was still running with the old provider name.

I've setup an additional daemon with the new provider name on the same port.

Thanks to this little old patch it works: https://github.com/Cofyc/dnscrypt-wrapper/commit/a9e2157ccf73e9da46f2442ffe6d1e94dd88d01c

**Comment by jedisct1** [comment]
No problem, Maciej!

And apparently, the patch still works well :)

**Pull request merged**
