### PR TITLE
https://dns.d0wn.biz/

### PR DESCRIPTION
**Pull request by Opensourcecommunitydevelopment**
DNS-Server:		ns1.de.dns.d0wn.biz
IPv4:			82.211.31.248
IPv6:			2001:1608:10:195:3:dead:beef:cafe
Location:		Germany
Provider-Key:		D4A8:6FB5:AA0C:2B6B:8C13:8C29:7F69:F9C8:29C8:E157:F279:6FC7:7366:290F:2A80:0AD2
Provider-Name:		2.dnscrypt-cert.de.d0wn.biz
Ports:			54 80 443 1053 5353 27015
Key valid until:	2016-10-31
Pubkey TXT Record:	pubkey.de.dnscrypt.d0wn.biz

### CODE REVIEW

**Comment by jedisct1** [comment]
How common is it that port 80 is accessible and allows non-HTTP traffic, but port 443 doesn't?

**Comment by Opensourcecommunitydevelopment** [comment]
hello, you are fast in response. this maybe very uncommon sure. but i just want to add all possible resolver and reachabillty to resolver list as where they are listening on. dont want to continue doing this locally because merging with the master csv takes time if done on my own. so i want to provide this or is this unwanted in main? btw. my last request that included a server and ipv6 from http://dnsrec.meo.ws/ disappeared. but iam new using github..

**Comment by jedisct1** [comment]
Not sure that this is useful to have many entries that are actually all the same server.

At some point, the CSV file can be changed to include a list of ports instead of a single port for a given entry. Meanwhile, duplication is not good:
- If port 443 is not reachable, it's unlikely that other ports on the same IP are going to work either
- It causes a bias for user interfaces randomly choosing the default server.

The other pull request was merged, but then reverted. The `fvz-rec-de-muc-01-ipv6` entry is actually not an IPv6 address.

**Comment by Opensourcecommunitydevelopment** [comment]
i have seen ipv6 have own entry for same server but different protocol. so i thought same applies with ports.

Well this would result into 12! entrys for one server. if all combinations are added.:
[2001:1608:10:195:3:dead:beef:cafe]:54 
[2001:1608:10:195:3:dead:beef:cafe]:80 
[2001:1608:10:195:3:dead:beef:cafe]                   (443 default)
[2001:1608:10:195:3:dead:beef:cafe]:1053 
[2001:1608:10:195:3:dead:beef:cafe]:5353 
[2001:1608:10:195:3:dead:beef:cafe]:27015
82.211.31.248:54 
82.211.31.248:80 
82.211.31.248                   (443 default)
82.211.31.248:1053 
82.211.31.248:5353 
82.211.31.248:27015

csv with collum  list of ports would be nice. but than this also would be needed to be parsed by client. that would make extra coding neccessary, extra time spent for just ports? for now i thought this is ok with duplicated entry. let me know. i dont want to flood csv :)


-  Yes, in default firewalled usage scenarios. 
If client connects through Proxy/VPN/Tor. The Proxy Server may restrict ports reachabillty. Some Open VPNs refuse Ports other than 80;443 (i mean no port 53 here) While some Exit nodes reject port 443/80 but allow port 53. Have no sample in moment. But one of Top 10 Relays by Consensus Weight for example, block port 80 but allow 443;53. You can check in exit policy of consensus for relay. https://atlas.torproject.org/#details/81B75D534F91BFB7C57AB67DA10BCEF622582AE8

A leakage could happen:
If you use dnscrypt&tor you will browse https://github.com:443 over this torexitnode, dns query goes over it as well. But if you browse http://github.com:80, torclient will build a new circuit to exit that allows exiting to port 80. BUT dnscrypt query will not follow at this point. This is "okay" since dnsCRYPT encrypted. But you can watch dns resolving from different IP/Country because different exit. As Operator of Nameserver/Webservice.

This is rare but i try to argue why other ports may be usefull to be in the list as long as they are responding :) Another thing is throttling of ports by ISP. 

- i dont know, only use commandline version, no interfaces I believe if ports lists is added, interfaces would take long to implement this if ever. if i put second entry with same server different port. the interface you like should understant it allready now. :)

i see now. this is my fault. i create new one again. ok.

**Comment by jedisct1** [comment]
`[2001:1608:10:195:3:dead:beef:cafe]` doesn't seem to work, no matter what the port is :(

**Comment by licaon-kter** [comment]
@Opensourcecommunitydevelopment It's advised against using dnscrypt over Tor anyway

@jedisct1 Is that a real address or just a mockup? https://en.wikipedia.org/wiki/DEADBEEF ?

**Comment by Opensourcecommunitydevelopment** [comment]
@licaon-kter this is the real address :), source: 
https://servers.opennicproject.org/edit.php?srv=ns26.de.dns.opennic.glue
http://dnsrec.meo.ws/#fvz-rec-de-muc-01

@jedisct1 sorry - but for me it is up and running. Can you check again please? Here my output following as expected:

> ./dnscrypt-proxy.exe --test=1 --provider-name=2.dnscrypt-cert.de.d0wn.biz -r [2001:1608:10:195:3:dead:beef:cafe]:443 --provider-key=D4A8:6FB5:AA0C:2B6B:8C13:8C29:7F69:F9C8:29C8:E157:F279:6FC7:7366:290F:2A80:0AD2

`[NOTICE] Starting dnscrypt-proxy 1.6.1
[INFO] Generating a new session key pair
[INFO] Done
[ERROR] Unable to retrieve server certificates
[INFO] Refetching server certificates
[INFO] Server certificate #808464433 received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 5B8C:68CA:BE7B:8BB6:5D5F:ED0F:2210:A729:0CB0:C9BB:2AF1:78C7:0C1F:0F88:2CC9:5678`

**Pull request merged**
