### PR TITLE
+24 Resolvers Online

### PR DESCRIPTION
**Pull request by Opensourcecommunitydevelopment**
```
./dnscrypt-proxy  --test=1 -R   d0wn-lu-ns1
./dnscrypt-proxy  --test=1 -R   d0wn-lu-ns1
./dnscrypt-proxy  --test=1 -R   d0wn-lv-ns2
./dnscrypt-proxy  --test=1 -R   d0wn-lv-ns2
./dnscrypt-proxy  --test=1 -R   d0wn-nl-ns3
./dnscrypt-proxy  --test=1 -R   d0wn-nl-ns3-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-random-ns1-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-random-ns2-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-ro-ns1-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-ro-ns1
./dnscrypt-proxy  --test=1 -R   d0wn-se-ns1
./dnscrypt-proxy  --test=1 -R   d0wn-se-ns1-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-sg-ns2
./dnscrypt-proxy  --test=1 -R   d0wn-sg-ns2-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-ua-ns1
./dnscrypt-proxy  --test=1 -R   d0wn-ua-ns1-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-uk-ns1
./dnscrypt-proxy  --test=1 -R   d0wn-uk-ns1-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-us-ns1
./dnscrypt-proxy  --test=1 -R   d0wn-us-ns1-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-us-ns2
./dnscrypt-proxy  --test=1 -R   d0wn-us-ns2-ipv6
./dnscrypt-proxy  --test=1 -R   d0wn-tz-ns1
./dnscrypt-proxy  --test=1 -R   fvz-anyone-ipv6
./dnscrypt-proxy  --test=1 -R   fvz-anytwo-ipv6
[INFO] - [d0wn-lu-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is C3A7:70B1:A5C8:9D0B:2084:E468:9759:C787:CA52:6CD0:43F3:0C30:69E7:21F0:7868:127E
[INFO] - [d0wn-lu-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is C3A7:70B1:A5C8:9D0B:2084:E468:9759:C787:CA52:6CD0:43F3:0C30:69E7:21F0:7868:127E
[INFO] - [d0wn-lv-ns2] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 2EB8:D3FD:154C:34C3:254E:B97E:5B6F:53D1:2472:CD4C:67FA:0002:B190:DC48:9524:7F62
[INFO] - [d0wn-lv-ns2] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 2EB8:D3FD:154C:34C3:254E:B97E:5B6F:53D1:2472:CD4C:67FA:0002:B190:DC48:9524:7F62
[INFO] - [d0wn-nl-ns3] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 1642:E5B7:751B:D9B1:E042:11A6:CEE3:F403:CD05:99FE:02E3:0EA0:666A:8643:1F04:CC33
[INFO] - [d0wn-nl-ns3-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 1642:E5B7:751B:D9B1:E042:11A6:CEE3:F403:CD05:99FE:02E3:0EA0:666A:8643:1F04:CC33
[INFO] - [d0wn-random-ns1-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is F70A:0FBD:9923:4645:D3F2:8D5B:3412:65B1:C948:7AFD:A6F3:5AB6:2016:F560:F31E:5A2B
[INFO] - [d0wn-random-ns2-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 73D3:6BF3:F7A7:CFB2:2736:17E2:95F5:10EF:46E4:C26D:66F7:A843:D748:67A6:B657:B866
[INFO] - [d0wn-ro-ns1-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is F2C3:53F9:E0BA:6EA9:0EFB:EAF9:DA79:A488:1D4A:C666:A94E:C63B:7115:C66A:F0C8:954D
[INFO] - [d0wn-ro-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is F2C3:53F9:E0BA:6EA9:0EFB:EAF9:DA79:A488:1D4A:C666:A94E:C63B:7115:C66A:F0C8:954D
[INFO] - [d0wn-se-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 2802:12E4:8BED:A949:C6E3:21CA:C9C2:446C:2DA0:C20A:D5ED:4702:352B:4C1D:DBDF:DD1D
[INFO] - [d0wn-se-ns1-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 2802:12E4:8BED:A949:C6E3:21CA:C9C2:446C:2DA0:C20A:D5ED:4702:352B:4C1D:DBDF:DD1D
[INFO] - [d0wn-sg-ns2] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 1894:37C9:7D97:7E40:CFB0:89DE:2A6F:C5FD:14EB:F8C8:25E8:876C:643E:1B07:7169:A960
[INFO] - [d0wn-sg-ns2-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 1894:37C9:7D97:7E40:CFB0:89DE:2A6F:C5FD:14EB:F8C8:25E8:876C:643E:1B07:7169:A960
[INFO] - [d0wn-ua-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 0DF1:EDDF:3A0D:4B3D:E8CB:E050:1D1D:E4D5:F670:ED97:207C:8EFE:78A3:AA9C:8E50:0C72
[INFO] - [d0wn-ua-ns1-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 0DF1:EDDF:3A0D:4B3D:E8CB:E050:1D1D:E4D5:F670:ED97:207C:8EFE:78A3:AA9C:8E50:0C72
[INFO] - [d0wn-uk-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 3C10:972F:6C6C:6DAB:9DE8:6408:8F9C:2994:5744:1B3D:1A13:6CFE:3062:4233:B90C:A32D
[INFO] - [d0wn-uk-ns1-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 3C10:972F:6C6C:6DAB:9DE8:6408:8F9C:2994:5744:1B3D:1A13:6CFE:3062:4233:B90C:A32D
[INFO] - [d0wn-us-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 7D17:109F:F1AD:EDC3:9EE0:7BBF:BCA6:D8CD:A800:EBDF:6375:6F4B:DE4C:E24B:B007:A575
[INFO] - [d0wn-us-ns1-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 7D17:109F:F1AD:EDC3:9EE0:7BBF:BCA6:D8CD:A800:EBDF:6375:6F4B:DE4C:E24B:B007:A575
[INFO] - [d0wn-us-ns2] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 06D2:9502:8F68:858F:5DBD:7660:3A86:B740:49AA:9787:8E9F:29E7:2B94:1884:5C3B:0B67
[INFO] - [d0wn-us-ns2-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 06D2:9502:8F68:858F:5DBD:7660:3A86:B740:49AA:9787:8E9F:29E7:2B94:1884:5C3B:0B67
[INFO] - [d0wn-tz-ns1] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is 0E3B:2CBB:6F40:2F8C:0956:7CF8:8555:CADF:7F36:8BEC:AEB9:1675:7544:FCBF:F157:6560
[INFO] - [fvz-anyone-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is E737:6400:D646:0720:7D9D:29AB:A4C9:070C:4546:CEF7:0CFE:D62F:41E9:FEAA:C58F:6376
[INFO] - [fvz-anytwo-ipv6] does not support DNS Security Extensions
[INFO] + Namecoin domains can be resolved
[INFO] + Provider supposedly doesn't keep logs
[NOTICE] Starting dnscrypt-proxy 1.7.0
[INFO] Generating a new session key pair
[INFO] Done
[INFO] Server certificate with serial '0001' received
[INFO] This certificate is valid
[INFO] Server key fingerprint is E737:6400:D646:0720:7D9D:29AB:A4C9:070C:4546:CEF7:0CFE:D62F:41E9:FEAA:C58F:6376
```

### CODE REVIEW

**Comment by KrasnayaPloshchad** [comment]
@jedisct1 I think these resolvers should be accepted immidiately.

**Comment by jedisct1** [comment]
Hi, and thank you for your contribution!

Can you fix the conflicts so that it can be merged?

Also, make sure that short names (the second column) are unique. For example, IPv4 and IPv6 addresses of the same resolver should have a different name, so they show up differently in GUIs.

Thanks!

**Comment by KrasnayaPloshchad** [comment]
@jedisct1 On GitHub you can be allowed to modify the PR to fix the conflics.

**Comment by KrasnayaPloshchad** [comment]
@jedisct1 I seperate them into my gist, please check:
https://gist.github.com/KrasnayaPloshchad/f0b943c7b1b72c4103d569ecd0ae18c5

**Pull request closed without merging**
