### PR TITLE
Updating fvz servers to represent an updated list from dnsrec.meo.ws

### PR DESCRIPTION
**Pull request by Fusl**
I quite don't understand why you re-added the servers, but anyway... I got some providers to sponsor me (and with that the OpenNIC and DNSCrypt project) servers for running DNS Resolvers on them -> http://dnsrec.meo.ws/

### CODE REVIEW

**Comment by jedisct1** [comment]
These were on the web page you just referenced. That's quite confusing :(

Anyway, your changes have been merged. Glad to see that you got a sponsor for some of them!

**Comment by Fusl** [comment]
Yes, at the beginning it was a very big chaos I needed to clean up.

I didn't expect you to merge this so fast. I will need to open another pull request shortly for adding the provider/sponsor name to each individual server. I hope that's for you :)

**Comment by jedisct1** [comment]
No problem!

By the way, `fvz-rec-ca-mtr-01-ipv6` and `fvz-rec-fr-sxb-01` don't seem to be reachable at the moment.

**Comment by jedisct1** [comment]
```
+ fvz-rec-at-vie-01 - OK
+ fvz-rec-ca-mtr-01 - OK
- fvz-rec-ca-mtr-01-ipv6 - Failed
+ fvz-rec-ca-tor-01 - OK
+ fvz-rec-ca-tor-01-ipv6 - OK
+ fvz-rec-de-fra-01 - OK
+ fvz-rec-de-muc-01 - OK
+ fvz-rec-de-muc-01-ipv6 - OK
+ fvz-rec-fi-ulv-01 - OK
+ fvz-rec-fi-ulv-01-ipv6 - OK
+ fvz-rec-fr-par-01 - OK
- fvz-rec-fr-sxb-01 - Failed
- fvz-rec-fr-sxb-01-ipv6 - Failed
+ fvz-rec-gb-brs-01 - OK
+ fvz-rec-gb-lon-01 - OK
- fvz-rec-gb-lon-01-ipv6 - Failed
+ fvz-rec-gb-lon-02 - OK
+ fvz-rec-hk-ztw-01 - OK
+ fvz-rec-ie-du-01 - OK
+ fvz-rec-lt-vno-01 - OK
+ fvz-rec-nl-dro-01 - OK
+ fvz-rec-nl-fl-01 - OK
+ fvz-rec-nl-fl-01-ipv6 - OK
+ fvz-rec-no-osl-01 - OK
+ fvz-rec-nz-akl-01 - OK
+ fvz-rec-nz-akl-01-ipv6 - OK
- fvz-rec-ro-buh-01 - Failed
+ fvz-rec-ru-led-01 - OK
+ fvz-rec-ru-led-01-ipv6 - OK
+ fvz-rec-sg-ea-01 - OK
- fvz-rec-sg-ea-01-ipv6 - Failed
+ fvz-rec-us-dal-01 - OK
- fvz-rec-us-dal-01-ipv6 - Failed
+ fvz-rec-us-lax-01 - OK
+ fvz-rec-us-lax-01-ipv6 - OK
+ fvz-rec-us-ler-01 - OK
+ fvz-rec-us-ler-01-ipv6 - OK
+ fvz-rec-us-mia-01 - OK
+ fvz-rec-us-mia-01-ipv6 - OK
+ fvz-rec-us-sea-01 - OK
+ fvz-rec-us-sea-01-ipv6 - OK
```

**Comment by Fusl** [comment]
Can you quickly run the test again? The module seems to be having issues on the new server. I should get the issues hopefully fixed in the next days.

**Comment by jedisct1** [comment]
```
+ fvz-rec-at-vie-01 - OK
+ fvz-rec-ca-mtr-01 - OK
+ fvz-rec-ca-mtr-01-ipv6 - OK
+ fvz-rec-ca-tor-01 - OK
+ fvz-rec-ca-tor-01-ipv6 - OK
+ fvz-rec-de-fra-01 - OK
+ fvz-rec-de-muc-01 - OK
+ fvz-rec-de-muc-01-ipv6 - OK
+ fvz-rec-fi-ulv-01 - OK
+ fvz-rec-fi-ulv-01-ipv6 - OK
+ fvz-rec-fr-par-01 - OK
- fvz-rec-fr-sxb-01 - Failed
- fvz-rec-fr-sxb-01-ipv6 - Failed
+ fvz-rec-gb-brs-01 - OK
+ fvz-rec-gb-lon-01 - OK
- fvz-rec-gb-lon-01-ipv6 - Failed
+ fvz-rec-gb-lon-02 - OK
+ fvz-rec-hk-ztw-01 - OK
+ fvz-rec-ie-du-01 - OK
+ fvz-rec-lt-vno-01 - OK
+ fvz-rec-nl-dro-01 - OK
+ fvz-rec-nl-fl-01 - OK
+ fvz-rec-nl-fl-01-ipv6 - OK
+ fvz-rec-no-osl-01 - OK
+ fvz-rec-nz-akl-01 - OK
+ fvz-rec-nz-akl-01-ipv6 - OK
+ fvz-rec-ro-buh-01 - OK
+ fvz-rec-ru-led-01 - OK
+ fvz-rec-ru-led-01-ipv6 - OK
+ fvz-rec-sg-ea-01 - OK
- fvz-rec-sg-ea-01-ipv6 - Failed
+ fvz-rec-us-dal-01 - OK
- fvz-rec-us-dal-01-ipv6 - Failed
+ fvz-rec-us-lax-01 - OK
+ fvz-rec-us-lax-01-ipv6 - OK
+ fvz-rec-us-ler-01 - OK
+ fvz-rec-us-ler-01-ipv6 - OK
+ fvz-rec-us-mia-01 - OK
+ fvz-rec-us-mia-01-ipv6 - OK
+ fvz-rec-us-sea-01 - OK
+ fvz-rec-us-sea-01-ipv6 - OK
```

**Pull request merged**
