### PR TITLE
Adding fvz servers

### PR DESCRIPTION
**Pull request by Fusl**

### CODE REVIEW

**Comment by jedisct1** [comment]
World domination!

**Comment by jedisct1** [comment]
BTW, `fvz-rec-de-dus-01` seems to be down :( Is it temporary?

**Comment by jedisct1** [comment]
`fvz-rec-ro-bu-01` too.

**Comment by Fusl** [comment]
Thanks for merging!
> World domination!

Kind of, indeed :)
Both servers rebooted a couple of hours ago. Automatic module loading doesn't work yet for some reason, I still need to look into this issue.

**Pull request merged**
