### PR TITLE
Fix fvz-rec-de-dus-01, remove soon-to-be-shutdown server & add server…

### PR DESCRIPTION
**Pull request by Fusl**
… that was down temporarily

### CODE REVIEW

**Comment by jedisct1** [comment]
Almost there :)

    - fvz-rec-us-tx-02 - Failed

**Comment by Fusl** [comment]
Hi!

Thanks for merging and for the information. I deployed a new version of the kernel module across all my hosts a few minutes ago, it should be better now.

**Comment by jedisct1** [comment]
Just curious :) What does this interesting kernel module do?

**Comment by Fusl** [comment]
It's https://github.com/Cofyc/dnscrypt-wrapper just written as a kernel module so to be faster and without the memory footprint it has (it only uses 2MB of ram while making use of the already existing kernel stack).

**Comment by jedisct1** [comment]
That's pretty insane. Quite scary from a security perspective, but still really nice.

Are you planning to eventually put this on Github?

I'd have gone the other way round (userland TCP/IP stack), but having a dnscrypt server as a kernel module is definitely cool.

**Comment by Fusl** [comment]
> Are you planning to eventually put this on Github?

Not at this time, no. The code has been mostly written as a project at work but I will at one point re-write the entire code and with that release the code then.

**Pull request merged**
