### PR TITLE
Fix 99dnscrypt startup

### PR DESCRIPTION
**Pull request by CHEF-KOCH**
added --edns-payload-size=1280 (tried 15 different resolvers, seems somehow settings > 1252 are never accepted (you get always the error msg) - [RFC2671](https://www.ietf.org/rfc/rfc2671.txt)
iptables can be called separat without &&
removed duplicate resolver-list call
added ip_forward, it's nessary for NAT ([default disabled](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt) on STOCK kernels)
Fixed startup problem, dnscrypt-proxy wants the .csv first, if that is called after the resolver-name you always get an error ("Unable to read [/Users/j/src/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy-armdroid-armv7-a/system/etc/dnscrypt-proxy/dnscrypt-resolvers.csv]

Tested under Android 4.4.4 ~ M Prev1 (AOSP)

### CODE REVIEW

**Comment by jedisct1** [comment]
The default payload size is `1252`, because higher values are indeed known to cause issues on some networks.
So, explicitly adding `--edns-payload-size=1252` is not useful.

The proxy is called twice. Once in test mode, to make sure that the chosen resolver works before adding firewall rules, or else we would end up with a device without useable DNS.

And the second time, it should be called exactly with the same parameters, except not in test mode, so that we can start accepting connections and forward them to the resolver that was just tested.

After your changes, the second call to dnscrypt-proxy wouldn't do anything, as it doesn't even include a resolver name.

The order for `--resolver-name=` and `--resolvers-list` shouldn't make a difference. If it does, we have a different issue.

iptables rules are called after `&&` because enabling them if the previous commands failed would give an unusable device.

**Comment by jedisct1** [comment]
And unfortunately on Lollipop, the iptables rules don't work, even after enabling IP forwarding :(

**Comment by CHEF-KOCH** [comment]
Well I added _edns-payload-size_ in case someone tried a higher level, because on the www people always saying 4096 works, in fact not under Android, on Windows or Linux it works. Strange!

> Once in test mode, to make sure that the chosen resolver works before adding firewall rules, or else we would end up with a device without usable DNS.

That won't work, since the firewall rules are handled by DHCP/DNSMasq and will be flushed anyway right after dnsmasq is up. Maybe we can just remove --test, that should be done separat on Android. 


> After your changes, the second call to dnscrypt-proxy wouldn't do anything, as it doesn't even include a resolver name.

Can't confirm here, with the original code the resolver-name is unknown because android can't load the list and check them against the .csv. Opening the .csv and reading them before adding the name makes more sense. I tried both and if I first use the name I always get errors. Don't know why this is.


> The order for  --resolver-name=  and  --resolvers-list  shouldn't make a difference. If it does, we have a different issue.

As I said, I tried it and it ends up with errors every time. You can verify that by opening the terminal under Android and manual paste this into it. 

> And unfortunately on Lollipop, the iptables rules don't work, even after enabling IP forwarding :(

It works, but it needs some workarounds since dnsmasq needs to be compiled with different arguments, this is only on stock. Changing the dnsmas.conf doesn't overrides the hardcoded stuff, I don't know why Android 5+ does this.

**Comment by jedisct1** [comment]
`1280` is the MTU, not the maximum payload size inside a UDP packet. Some routers/firewalls drop fragments, others don't. I can't use anything above `1252` on my laptop either, due to the router. This is the default value for a reason, it shouldn't be blindly modified.

The test mode doesn't need to send anything to port 53. It only connects to the dnscrypt port and checks the validity of the server certificate. So dnsmasq and iptables rules related to port 53 should not interfere.

**Comment by CHEF-KOCH** [comment]
I think we are talking about different things. The MTU in Android 5 is broken, so it's always 1500, that doesn't have anything to do what the router can handle and what not. The payload size itself is fixed in dnsmasq. Android 5 comes with an pretty outdated dnsmasq binary on board, I solved that by using the [latest 2.75](http://www.thekelleys.org.uk/dnsmasq/doc.html) ([compared to 2.63+](http://www.thekelleys.org.uk/dnsmasq/CHANGELOG)). And tweaked the configuration, and viola it works. 

The reasons why Android 5+ seems to not work isn't because it can't obtain an valid IP it's because name resolution. If there is an interest I can upload my config, the only thing that doesn't work (not found out why atm, seems 3G/LTE/BT/WLan/VPN/[DHCPv6] tethering because DNS REFUSE) [on M it works].

**Comment by CHEF-KOCH** [comment]
I'm giving up in Android and DNSCrypt, I like the idea but that's it. There are certain problems that can't be fixed with scripts, I already did mentioned this twice but nobody seems listen to it:

* IPv6
* The entire netd problem; ndc
* Tethering problem (dnsmasq needs to be restarting every time)
* no "good interface" so that noobs can change that (only within the script which needs an file manager, well comes with almost every ROM but it's still somehow complicate even with the good documentation)

I now asked the CM team how they can fix this, but imho it's only possible to implement and chance the ROM or as app. Remember Android or iOS isn't Ubuntu which stays on the same connection every time, and because of this, it could never be done by an script - sorry but that's true. As long these mentioned problems are not solved (for everyone) this can't be used for a daily usage, or only if you not use IPv6/tethering/..... For people which wants to use the smartphone only as a smartphone this might be okay but that's it - for me it's a no-go to solve stuff that should be handled by the OS and not by additional steps/skrips workarounds. 

I generally think that the project is good on Windows/Linux and it works wonderful but for smartphone I can't recommend it until all mentioned problems are finally and for all fixed.

If there are news from the CM team I may re-answer here so that people can stay on-the-line. 

THX,
CK.

**Comment by jedisct1** [comment]
The solution is probably to use the VpnService framework, similar to what is will be done on iOS 9.

**Pull request closed without merging**
