### PR TITLE
Updating Babylon Network resolvers

### PR DESCRIPTION
**Pull request by tsemeijn**
Updating Babylon Network resolvers to reflect Canadian resolver being shut down for now and changing IP address of the fr1 resolver.

### CODE REVIEW

**Comment by jedisct1** [comment]
Merged. Sorry for the delay!

**Comment by jedisct1** [comment]
`bn-fr1` doesn't seem to work...

**Comment by jedisct1** [comment]
```sh
$ drill -p 5353 txt 2.dnscrypt-cert.babylon.network @164.132.130.171
Error: error sending query: Could not send or receive, because of network error
```

Nothing on port 5353 :(

**Comment by tsemeijn** [comment]
Should be fixed now. Please try again ;)

**Comment by jedisct1** [comment]
Looks fine now, thanks!

**Pull request merged**
