### PR TITLE
Update dnscrypt-proxy.service

### PR DESCRIPTION
**Pull request by AladW**
Drop priviledges to nobody user (cf. OS X service) and add ephemeral keys

### CODE REVIEW

**Comment by jedisct1** [comment]
`nobody` was designed for NFS, and is not something to run unrelated service as. Dedicated system accounts should be used instead.

Ephemeral keys are not on by default because it's taxing on the CPU, especially on non-Intel platforms, and because it's useless with most DNSCrypt servers (all the servers using short TTLs for the certificates, which is done by default in the docker image).

**Comment by AladW** [comment]
Would `-u dnscrypt` be acceptable? If yes, the OS X .plist should be changed accordingly.

**Comment by lahwaacz** [comment]
The user for `-u` must exist on the system in the first place. And root rights are needed to listen to the default [privileged](http://stackoverflow.com/questions/10182798/why-are-ports-below-1024-privileged) port 53, unless the privileges are dropped afterwards.

**Comment by AladW** [comment]
The usage section mentions:
>Having a dedicated system user, with no privileges and with an empty home directory, is highly recommended. For extra security, DNSCrypt will chroot() to this user's home directory and drop root privileges for this user's uid as soon as possible.
I don't think assuming a new user in the service file is a big issue, if the user installed manually with Make he can also create a user, and a distro packager can do the same.

**Comment by jedisct1** [comment]
The `.service` file was updated to  suggest using a dedicated user.

A side effect is that it doesn't work any more by default :(

**Comment by AladW** [comment]
I noticed it was added anyway: https://github.com/jedisct1/dnscrypt-proxy/commit/45884045caf88bc136e12c4ad0f9e57334feec61
Thanks :+1:

**Comment by jedisct1** [comment]
That was bound to happen: https://bugs.archlinux.org/task/50224

**Pull request closed without merging**
