### PR TITLE
Adding IPv6 version of fvz resolvers

### PR DESCRIPTION
**Pull request by Fusl**
Please let me know if something is wrong (format, server unreachable, etc.), but everything should be fine from what I can see.

### CODE REVIEW

**Comment by jedisct1** [comment]
Fantastic!

I don't have IPv6 connectivity right now, but I will check this as soon as I get back home.

**Comment by jedisct1** [comment]
Hello,

Looks like none of them is useable. The reason might be that they don't respond to the certificate request. Or rather, they respond with NXDOMAIN instead of the certificates:

```bash
$ drill -p 443 txt dnscrypt-cert.fvz-rec-at-vie-02.dnsrec.meo.ws @2a03:f80:ed16:ca7:ea75:b12d:1b9:e6b9
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 2910
```

**Comment by Fusl** [comment]
Hi,

you have the "2." missing there. It is "2.dnscrypt-cert.fvz-rec-at-vie-02.dnsrec.meo.ws", not "dnscrypt-cert.fvz-rec-at-vie-02.dnsrec.meo.ws" :-)

**Comment by jedisct1** [comment]
Good catch. Wondering who designed such as terrible protocol, haha.

The actual reason it doesn't work is that IPv6 addresses require the port number after the address.
It should be optional, and this is something I definitely need to fix. Meanwhile, I'm just gonna add `:443` after the resolvers IPs and everything should magically work :)

**Comment by Fusl** [comment]
Please let me know if you want me to add :443 to the end of the IPv4/IPv6 addresses. It's not a big deal, just 2 changes in the template file.

**Comment by jedisct1** [comment]
Don't worry, I'm gonna do it. But it doesn't hurt doing it on your side for the future resolvers :)

**Comment by jedisct1** [comment]
They all work except `fvz-rec-de-fra-02-ipv6`.

**Comment by Fusl** [comment]
Hi,

hm, fvz-rec-de-fra-02-ipv6 doesn't seem to be in the database, I wonder why I added it there. You can just remove it from the file. I will delete the interface for it. Provider is just too stupid to fix the IPv6 connectivity again :(

**Comment by jedisct1** [comment]
Can you confirm the IP of `fvz-rec-de-fra-02-ipv6`?

**Comment by jedisct1** [comment]
No worries, I'm gonna remove it, then.

Thanks for providing these IPv6 resolvers! Perfect timing now that the world just ran out of IPv4 addresses!

**Comment by jedisct1** [comment]
Merged! All of them are working fine!

**Comment by jedisct1** [comment]
Oh, just one details: it's better to have a unique name (second column) for each resolver (maybe just by adding "IPv6" at the end).
Because some user interfaces just display this name and not the id from the first column, so we see the same things twice.

**Comment by jedisct1** [comment]
Also, there was an extra space after the name and before the "," :)

**Comment by Fusl** [comment]
All of these things should be fixed now in the exporter template. Mind taking a look at the recent export? https://scr.meo.ws/paste/2015-09-23-22-17-59-Xje2py0v.txt

**Comment by jedisct1** [comment]
Looks perfect! :+1:

**Pull request merged**
